name: 'check-debug-statements'
description: 'github action template for check constructions "dd" and "console.log" in files'
author: 'Fedor Khodyrev <xodyrev.fedya@mail.ru>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'eye'  
  color: 'gray-dark'
